spring:
  datasource:
    url: jdbc:mysql://173.212.221.237:33306/workers?createDatabaseIfNotExist=true
    username: root
    password: root12
    tomcat:
      test-while-idle: true
      validation-query: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true